repos:
  -   repo: https://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
      -   id: isort
          args: [ "--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3.12

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    - id: add-trailing-comma

  - repo: https://github.com/hakancelik96/unimport
    rev: 1.1.0
    hooks:
      - id: unimport
        args: [-r, --include-star-import]
